name: platform_channel_events
description: A new Flutter application demonstrating how to stream data via platform event channels.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  google_maps_flutter: any
  equatable: 2.0.3
  flutter_bloc: any
  sqflite: any


dev_dependencies:
  effective_dart: ^1.3.1

flutter:
  uses-material-design: true
  assets:
    - assets/
